config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :meals do
    resources :ingredients
  end

  resources :days

  resources :lists

  get 'ingredients' => 'ingredients#new'

end

app/models/day.rb
class Day < ActiveRecord::Base
	validates :number, presence: true

	# attr_accessor :meals

	def day_meals
		if meals.present?
			meals.map do |meal|
				Meal.find(meal.to_i)
			end
		else
			[]
		end
	end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	belongs_to :meal

	validates :name, presence: true, length: {maximum:50, minimum: 3 }
	validates :meal_id, presence: true

	def self.for_list
		Ingredient.where(list_id: '1')
	end

	def is_on_list?
		list_id.present?
	end
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :ingredients

	def self.has_ingredient(ingredient)
		Ingredient.where(list_id: 1).each do |list_ingredient|
			if list_ingredient.name == ingredient.name
				return list_ingredient.id
			end
		end
		return nil
	end

	def self.ingredients_list
		Ingredient.where(list_id: 1)
	end
end

app/models/meal.rb
class Meal < ActiveRecord::Base
	has_many :ingredients

	validates :name, presence: true, length: {maximum:50, minimum: 3 }

	def ingredients_list
		Ingredient.where(meal_id: id).where(list_id: nil)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/days_controller.rb
class DaysController < ApplicationController

	def index
		@meals = Meal.all
		@days = Day.all.order(number: :asc)
	end

	def update
		Day.find(params[:id]).update_attributes(meals: params[:meals])
		render :json => { :success => "success", :status_code => "200" }
	end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

	def new
		@meal = Meal.find(params[:meal_id])
		@meal_name = @meal.name
		@ingredient = Ingredient.new(meal_id: params[:meal_id])
		@units = YAML.load_file("#{Rails.root}/config/units.yml")
	end

	def create
		@ingredient = Ingredient.new(ingredient_params)
		@ingredient.meal_id = params[:meal_id]
		@ingredient.save

		redirect_to meal_path(params[:meal_id])
	end

	def ingredient_params
    params.require(:ingredient).permit(:name, :quantity, :quantity_units)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

	def index
		# placing this in index until users are implemented
		# this is where some user functionality would go... Lists.where(user_id: user_id)
		@ingredients = Ingredient.where(list_id: '1').order(id: :asc)
		render '/lists/show'
	end

	def new
		# update when users are implemented
		Ingredient.for_list.delete_all

		days = Day.all.order(number: :asc)

		days.each do |day|
			day.day_meals.each do |meal|
				meal.ingredients_list.each do |ingredient|
					if list_ingredient=List.has_ingredient(ingredient)
						active_ingredient = Ingredient.find(list_ingredient)
						active_ingredient.quantity += ingredient.quantity
						active_ingredient.save!
					else
						new_ingredient = ingredient.dup
						new_ingredient.list_id = 1
						new_ingredient.save!
					end
				end
			end
		end

		redirect_to lists_path
	end

	def update
		Ingredient.find(params[:id]).update_attributes(purchased: params[:status])
		render :json => { :success => "success", :status_code => "200" }
	end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
  	@meals = Meal.all
  end

  def show
  	@meal = Meal.find(params[:id])
  end

  def new
  	@meal = Meal.new
  	@meal.name = "New Meal"
  end

  def create
  	@meal = Meal.create(meal_params)
  	redirect_to meal_path(@meal)
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def update
    Meal.find(params[:id]).update_attributes(meal_params)
    redirect_to meal_path(Meal.find(params[:id]))
  end

  def meal_params
    params.require(:meal).permit(:name, :image, :recipe)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/days/index.html.erb
<div class="row">
	<div class="large-12 columns">
		<div class="meal-box panel">
			<ul>
				<% @meals.each do |meal| %>
			  	<li class="meal draggable" meal="<%=meal.id%>">
			  		<i class="fa fa-ellipsis-v"></i>
      			<%= image_tag meal.image %>
      			<div class="day-meal-name">
      				<span><%= meal.name %></span>
      			</div>
    			</li>
			  <% end %>
			</ul>
		</div>
	</div>
</div>

<div class="row">
	<% @days.each do |day| %>
		<div class="large-3 columns end day-block">
      <div class="panel">
        <h4 class="day-title"><%= day.name %></h4>
        <h6 class="subheader">
        	<hr/>
        	<% if day.meals.nil? || day.meals.length == 0 %>
        		<ul class="sortable" id="<%= day.number %>">
        		</ul>
        	<% else %>
        		<ul class="sortable" id="<%= day.number %>">
	        		<% day.day_meals.each do |meal| %>
	        			<li class="meal" meal="<%=meal.id%>">
	        				<i class="fa fa-ellipsis-v"></i>
		        			<i class="fa fa-times remove" id="<%= day.number %>"></i>
		        			<%= image_tag meal.image %>
		        			<div class="day-meal-name">
		        				<span><%= meal.name %></span>
		        			</div>
	        			</li>
	        		<% end %>
        		</ul>
        	<% end %>
        </h6>
      </div>
    </div>
	<% end %>
	<%= link_to "Grocery List", new_list_path, class: "large-3 columns end button" %>
</div>


<script>
	$(function() {
	  $( ".sortable" ).sortable({
		  update: function( event, ui ) {
		  	$('.placeholder').remove();
		  	id = event.target.id
		  	updateDay(id)
		  }
		});

		$( ".sortable" ).sortable({
      connectWith: ".sortable",
      placeholder: "placeholder"
    });

	  $( ".sortable" ).disableSelection();

	  $( ".draggable" ).draggable({
      connectToSortable: ".sortable",
      helper: "clone",
      revert: "invalid",
      stack: ".draggable"
    });

    $(".remove").click(function() {
    	id = $(this).attr("id")
  		$(this).parent().remove();
  		updateDay(id)
		});

		function updateDay(id){
			el = $("#"+id)
			$.ajax({
		    url: "/days/"+id,
		    type: 'PUT',
		    data: { meals: el.sortable("toArray", {attribute: "meal"}) },
		    error: function(result) {
		    	alert("Uh oh! Something went wrong! Try reloading this page");
		    }
			});
		}
	});
</script>

app/views/ingredients/new.html.erb
<div class="row">
	<div class="large-6 large-centered columns">  
		<h1>New Ingredient</h1>
		<h3><%= @meal_name %></h3>
		<%= simple_form_for [@meal, @ingredient] do |f| %>
			<%= f.input  :name %>
			<%= f.input  :quantity %>
			<%= f.input  :quantity_units, collection: @units %>
			<%= f.button :submit %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Recip.me" %></title>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<%= render 'static_pages/header' %>
    <%= yield %>
    <%= render 'static_pages/footer' %>
  </body>
</html>

app/views/lists/show.html.erb
<div class="row">
	<div class="large-8 large-centered columns">
		<h1>Grocery List</h1>
		<table class="list">
			<% @ingredients.each do |i| %>
				<tr id="row_<%=i.id%>">
					<td class="name"><%= i.name %></td>
		      <td class="quantity"><input type="text" value="<%= i.quantity %>"/></td>
					<td class="unit"><%= i.quantity_units %></td>
					<td>
						<div class="switch radius">
						  <input id="switch_<%=i.id%>" checked type="checkbox" data-id="<%=i.id%>" data-initial="<%=i.purchased%>">
						  <label for="switch_<%=i.id%>"></label>
						</div> 
					</td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

<script>
	$(function() {

		$("input[id^='switch_']").click(function() {
	  	id = $(this).data("id");
	  	el = $("#row_"+id);

	  	if($(this).is(':checked')){
	  		light(el, id);
	  		purchase(id, false);
	  	}else{
	  		dim(el, id);
	  		purchase(id, true);
	  	}
		});

		darkenPurchased();

		function darkenPurchased() {
			switches = $("[data-initial='true']");
			switches.click();

			$.each(switches, function(index, item) {
				getRow($(item)).css("background-color", "DimGray");
			});
		}

		function purchase(id, status) {
			$.ajax({
		    url: "/lists/"+id,
		    type: 'PUT',
		    data: { status: status },
		    error: function(result) {
		    	alert("Uh oh! Something went wrong! Try reloading this page");
		    }
			});
		}

		function unpurchase(id) {

		}

		function getRow(box) {
			id = box.data("id");
	  	return $("#row_"+id);
		}

		function dim(el, id) {
			el.css("background-color", "DimGray");
		}

		function light(el, id) {
			el.css("background-color", "#49AA25");
		}
	});
</script>

app/views/meals/edit.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
    <%= simple_form_for @meal do |f| %>
      <%= f.input :name %>
      <%= f.input :image %>
      <%= f.input :recipe %>
      <%= f.button :submit, 'Update' %>
    <% end %>
    <h2>You can add the ingredients after creating your meal</h2>
  </div>
</div>

app/views/meals/index.html.erb
<div class="row">
  <div class="large-12 columns">  
    <div class="row">
      <div class="large-4 small-12 columns">
        <%= image_tag 'Vitamins-from-Food.jpg' %>
        <div class="hide-for-small panel">
          <h3>Meals</h3>
          <h5 class="subheader">
          	Here you can find all your delicious meal ideas!
          </h5>
          <%= link_to "New Meal", new_meal_path, class: "button" %>
        </div>
      </div>

      <div class="large-8 columns">
        <% @meals.each_slice(3) do |slice| %>
          <div class="row">
            <% slice.each do |meal| %>
              <div class="large-4 small-6 columns end" id="image-block">
                <%= image_tag meal.image, class: 'meal-image' %>
    
                <div class="panel">
                  <h4 class="meal-title"><%= meal.name %></h4>
                  <h6 class="subheader">
                  	<%= "#{meal.ingredients_list.length} 
                  			ingredients" %>
                  </h6>
                  <%= link_to "View", meal_path(meal), class: "button" %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/meals/new.html.erb
<div class="row">
	<div class="large-6 large-centered columns">
		<%= simple_form_for @meal do |f| %>
			<%= f.input :name %>
			<%= f.input :image %>
      <%= f.input :recipe %>
			<%= f.button :submit, 'Create Meal' %>
		<% end %>
		<h2>You can add the ingredients after creating your meal</h2>
	</div>
</div>

app/views/meals/show.html.erb
<div class="row">

	<div class="show-meal large-10 large-push-3 columns">
		<h1 class="meal-title"><%= @meal.name %></h1>
		<br/>
		<p><%= link_to "Recipe", @meal.recipe, target: "_blank" %></p>
		<h2><em>Ingredients:</em></h2>
		<br/>
		<table>
			<thead>
				<th>Name</th>
				<th>Quantity</th>
				<th>Unit</th>
				<th>Modify</th>
			</thead>
			<tbody>
				<% @meal.ingredients_list.each do |ingredient| %>
					<tr>
						<td><%= ingredient.name %></td>
						<td><%= ingredient.quantity %></td>
						<td><%= ingredient.quantity_units %></td>
						<td>Edit / Delete</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>

	<div class="large-2 large-pull-10 columns">
	  <div class="icon-bar vertical five-up">
	  	<%= link_to meals_path, class: "item" do %>
		    <i class="fa fa-arrow-left"></i>
		    <label>Back</label>
		  <% end %>
		  <%= link_to new_meal_ingredient_path(@meal), class: "item" do %>
		    <i class="fa fa-plus"></i>
		    <label>Add Ingredient</label>
		  <% end %>
		  <%= link_to edit_meal_path(@meal), class: "item" do %>
		    <i class="fa fa-pencil"></i>
		    <label>Edit Meal</label>
		  <% end %>
		  <a class="item">
		    <i class="fa fa-trash-o"></i>
		    <label>Delete Meal</label>
		  </a>
		  <a class="item">
		    <i class="fa fa-cart-plus"></i>
		    <label>Add to This Week</label>
		  </a>
		</div>
	</div>


</div>

app/views/static_pages/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Recip.me</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact Us</a></li>
          <li><a href="#">Sign Up</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/static_pages/_header.html.erb
<div class="row">
	<div class="large-2 columns">
		<h1>Recip.me</h1>
	</div>
  <div class="large-9 columns">
    <ul class="button-group right">
      <li><%= link_to "Meals", meals_path, class: "button" %></li>
      <li><%= link_to "Week", days_path, class: "button" %></li>
      <li><%= link_to "Grocery List", lists_path, class: "button" %></li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <hr/>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <!-- <img src="http://placehold.it/1000x400&text=[img]"> -->
    <%= image_tag 'main_food.jpg' %>
    <hr>
  </div>
</div>
 
<div class="row">
  <div class="large-4 columns">
    <!-- <img src="http://placehold.it/400x300&text=[img]"> -->
    <%= image_tag 'chinese-food-therapy.jpg' %>
  </div>
  <div class="large-8 columns">
    <h4>Fresh meals made from fresh ingredients!</h4>
    <div class="row">
      <div class="large-6 columns">
        <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
      </div>
      <div class="large-6 columns">
        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-8 columns">
    <h4>Store your meals, ingredients, and more!</h4>

    <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>

    <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>

  </div>
  <div class="large-4 columns">
    <!-- <img src="http://placehold.it/400x300&text=[img]"> -->
    <%= image_tag 'Delicious-Food-.jpg' %>
  </div>
</div>